Rent model
wolox-training/mlc-rails pull request #12
Opened 2018-11-02 15:52 UTC by micaelacole

# Summary
A Rent model is created, with references to the User and Book models, and date-type fields for the start date and end date of the rental.

After creating the model with its migration, a Rent instance can be created within the Ruby console (irb). Since it references or _belongs_to_ certain book and user, it is necessary to create an instance of these two classes first. For example:

-  `User.create(first_name: "Test", last_name: "TestLastName", email: "test@wolox.com.ar", password: "123123123", password_confirmation: "123123123")`

- `Book.create(genre: "Fantasy", title: "The Chronicles of Narnia: The Lion, the Witch and the Wardrobe", author: "C. S. Lewis", cover_image: "narnia_cover.jpg", publisher: "Geoffrey Bles", year: "1950")`

- `Rent.create(user: User.first, book: Book.first, start_date: Date.new(2018, 8, 5), end_date: Date.new(2018, 8, 9))`

With those three tasks, a Rent instance can be created, returning: `#<Rent id: 1, user_id: 1, book_id: 1, start_date: "2018-08-05", end_date: "2018-08-09", created_at: "2018-10-30 20:11:04", updated_at: "2018-10-30 20:11:04">`

# Trello Card
https://trello.com/c/B98A8RY0

2018-11-02 16:18 UTC, nicozar95 requested changes

2018-11-02 16:18 UTC, nicozar95 commented on spec/factories/rents.rb
> +    start_date { 'MyString' }
Don't use constant in a factory

2018-11-02 19:59 UTC, facucompe requested changes

2018-11-02 19:59 UTC, facucompe commented on app/controllers/books_controller.rb
> +    @books = Book.all
There is no need to use a instance variable, you can do `render_paginated Book.all`

2018-11-02 19:59 UTC, facucompe commented on app/controllers/books_controller.rb
> +    @book = Book.find(params[:id])
Same here

2018-11-02 19:59 UTC, facucompe commented on spec/controllers/books_controller_spec.rb
> +        expect(response.body.to_json) =~ BookSerializer.new(
Add this:
```
module Response
  module JSONParser
    def response_body
      ActiveSupport::JSON.decode(response.body) if response.present? && response.body.present?
    end
  end
end
```
So you can do `response_body`.

2018-11-05 20:17 UTC, nicozar95 commented on spec/factories/rents.rb
> +    user
Why is the user and book empty on the Factory?

2018-11-05 20:22 UTC, micaelacole commented on spec/factories/rents.rb
> +    user
I looked up how to create a Factory of an object that references on other objects and found this solution. What I understood from it is that in this way we can call the User and Book factories in order to create the Rent factory. I think I tried doing FactoryBot.create(rent) and it worked, but I'm gonna try it one more time to be sure.

2018-11-06 13:04 UTC, nicozar95 commented on spec/factories/rents.rb
> +    user
You can call directly to create a user in a FactoryBot, for example:
``` 
FactoryBot.define do
  factory :rent do
    user { create(:user) }
    ...
  end
end
```

2018-11-07 16:28 UTC, nicozar95 requested changes
I think there it's a little of mixed features in this PR 😕

2018-11-07 16:28 UTC, nicozar95 commented on app/controllers/books_controller.rb
> +class BooksController < ApplicationController
What does this had to do with the card? 🤔

2018-11-07 16:30 UTC, micaelacole commented on app/controllers/books_controller.rb
> +class BooksController < ApplicationController
I merged the other approved PRs into this one.

2018-11-07 16:30 UTC, nicozar95 commented on app/controllers/books_controller.rb
> +class BooksController < ApplicationController
You should have rebase the changes

2018-11-07 19:29 UTC, nicozar95 submitted a review, later dismissed
Remove unecesary files and it's well to go

2018-11-07 19:29 UTC, nicozar95 commented on spec/models/rent_spec.rb
> +require 'rails_helper'
Remove this file

2018-11-07 19:29 UTC, nicozar95 commented on spec/controllers/rents_controller_spec.rb
> +require 'rails_helper'
Remove this file... for now

2018-11-12 15:41 UTC, facucompe approved these changes

2018-11-12 17:37 UTC, merged