Rubocop config
wolox-training/mlc-rails pull request #2
Opened 2018-10-22 18:11 UTC by micaelacole

# Summary

Implementation of Rubocop. When the following command is executed:
`bundle exec rubocop app -R`

The files are inspected and no offenses in the application are detected by Rubocop. This is the expected behaviour of the card for it to being considered successful.

# Trello Card

https://trello.com/c/8LREWGyD

2018-10-23 16:27 UTC, nicozar95 requested changes
Fix the conflicts and fix why it's showing 1575 files show 
![image](https://user-images.githubusercontent.com/11698687/47375759-5eac8280-d6c7-11e8-8e9b-2c7f584e3d0c.png)

2018-10-23 17:43 UTC, facucompe requested changes

2018-10-23 17:43 UTC, facucompe commented on .rubocop.yml
> +  Max: 99
Always leave an empty line at the bottom of the file

2018-10-23 17:43 UTC, facucompe commented on Gemfile
> +# frozen_string_literal: true
We don't want this comment. You can disable rubocop rules.
Add this to the **rubocop.yml**
```
Style/FrozenStringLiteralComment:
  Enabled: false
```

2018-10-23 17:43 UTC, facucompe commented on Gemfile
> +# frozen_string_literal: true
Also remove all the comments from all files. Sorry for that :grimacing:

2018-10-23 19:03 UTC, nicozar95 requested changes

2018-10-23 19:03 UTC, nicozar95 commented on app/models/user.rb
> +            # Include default devise modules.
Why is this here? what is devise? we are installing rubocop on this PR not devise :p

2018-10-23 20:56 UTC, nicozar95 approved these changes

2018-10-23 21:24 UTC, facucompe requested changes
Remember removing the top comments from all files

2018-10-24 14:56 UTC, facucompe approved these changes

2018-10-24 16:13 UTC, merged